/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGreenBadgeNFT,
  IGreenBadgeNFTInterface,
} from "../../../contracts/GreenProof.sol/IGreenBadgeNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "level",
        type: "uint8",
      },
    ],
    name: "hasLevel",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "level",
        type: "uint8",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGreenBadgeNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IGreenBadgeNFTInterface {
    return new Interface(_abi) as IGreenBadgeNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGreenBadgeNFT {
    return new Contract(address, _abi, runner) as unknown as IGreenBadgeNFT;
  }
}
