/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GreenProof__factory } from "./GreenProof__factory";
export { IGreenBadgeNFT__factory } from "./IGreenBadgeNFT__factory";
