/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as greenProofSol from "./GreenProof.sol";
export { GreenBadgeNFT__factory } from "./GreenBadgeNFT__factory";
