/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greenProofSol from "./GreenProof.sol";
export type { greenProofSol };
export type { GreenBadgeNFT } from "./GreenBadgeNFT";
