name: Deploy Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    concurrency: pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (frontend)
        working-directory: frontend
        run: npm ci || npm i --no-audit --no-fund
      - name: Build and export static
        working-directory: frontend
        run: |
          npm run build
          npm run export
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/out
          publish_branch: gh-pages
          force_orphan: true

